config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :posts
  get 'index' => 'practice#index'
  post 'index' => 'practice#index'
  get 'about' => 'practice#about'
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
		devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(id: @comment.post_id)}
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :post_id, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :blog_entry, :user_id)
    end
end

app/controllers/practice_controller.rb
class PracticeController < ApplicationController
  def index
  	@name = params[:name]
  end

  def about
  	@color = params[:color]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/practice_helper.rb
module PracticeHelper
end

app/views/comments/_form.html.erb
<h3>Comment:</h3>

<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group">
    <%= form.text_area :comment_entry, placeholder: "Tell Me Something...", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :post_id, value: @post.id %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
to<!DOCTYPE html>
<html>
  <head>
    <title>Clog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="container">
        <div class="pull-right">

          <% if user_signed_in? %>
            <% if current_user.avatar.url %>
              <%= image_tag current_user.avatar.url, size: 50 %>
            <% end %>
            <p>Welcome <%= current_user.username %></p>
            <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary" %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, placeholder: "Blog Entry Title", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group">
    <%= form.text_area :blog_entry, placeholder: "Tell us something...", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Blog entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.user.username %></td>
        <td><%= post.blog_entry %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<h1>	
  <%= @post.title %>
</h1>

  
 <%= @post.user.username %> posted <%= time_ago_in_words(@post.created_at) %> ago
<p>
 	<%= @post.created_at.strftime("Posted on %m/%d/%Y which was a %A") %>	
</p>



<div class="panel panel-primary">
  <%= @post.blog_entry %>	
</div>


<% @post.comments.each do |comment| %>
	<div class="panel panel-default">
		<div class="panel-heading panel-primary">
			<p><b><%= comment.user.username %></b> said <%= time_ago_in_words(comment.created_at) %> ago</p>
		</div>
		<div class="panel-body">
			<p><%= comment.comment_entry %></p>
		</div>
	</div>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %>

<div id="comments">
	<%= render 'comments/form', comment: @comment %>
</div>

<%= link_to 'Back', posts_path %>

app/views/practice/about.html.erb
<h1>Practice#about</h1>
<p>Find me in app/views/practice/about.html.erb</p>

<style>
	#color_me_in {
		background-color: <%= @color %>;
		color: white;
		width: 250px;
		height: 250px;
	}
</style>

<div id="color_me_in">
	<p>
		<%= @color.upcase %> BOX ACTIVATED!
	</p>
</div>

<%= form_tag index_path do %>
	<p><%= text_field_tag :name, nil, placeholder: "What's your name?" %></p>
	<p><%= submit_tag :submit %></p>

<% end %>

Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda ab explicabo, perferendis a, ullam voluptatum quo harum. Aperiam laborum incidunt corrupti quos porro, sint qui possimus obcaecati dolorem, earum natus.

app/views/practice/index.html.erb
<h1>Choose a color!</h1>

<% if !@name.blank? %>
	<h2>Welcome Back, <%= @name %></h2>
<% end %>

<p>
	<%= link_to "Red", about_path(color: "red") %>
</p>

<p>
	<%= link_to "Blue", about_path(color: "blue") %>
</p>

<p>
	<%= link_to "Green", about_path(color: "green") %>
</p>

<p>
	<%= link_to "Yellow", about_path(color: "yellow") %>
</p>